name: kafka-event-forwarder-nodejs
namespace: backend
runtime: node
image: quay.io/redhatdemo/2021-kafka-event-forwarder-nodejs
imageDigest: ""
trigger: http
builder: default
builderMap:
  default: quay.io/boson/faas-nodejs-builder
envVars:
  KAFKA_BOOTSTRAP_URL: localhost:9092
  NODE_ENV: dev
