apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kafka-forwarder-attack
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: attack
  subscriber:
    uri: http://event-forwarder.kafka-streams.svc.cluster.local/
