apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kafka-forwarder-attack
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: attack
  subscriber:
    uri: uri: http://kafka--event--forwarder--nodejs.frontend.svc.cluster.local:80/
