apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kafka-forwarder-match-end
  namespace: battleships-backend
spec:
  broker: default
  filter:
    attributes:
      type: match-end
  subscriber:
    uri: http://kafka-event-forwarder.svc.cluster.local:8080/events/trigger
